### ISSUE TITLE
Grouped products not associated on import

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#34]
_From @adamlavery on October 18, 2017 9:51_

When importing grouped products, the simple products are imported but not associated with the group product.

Magento OS v2.2.0

Steps to reproduce:
1. Setup and export grouped product, including simple associated products.
2. Delete grouped product and simple products.
3. Wait for re-index. (+1 to restore re-index option from admin).
3. Import using the unmodified export file generated.

Expected result:
1. Grouped/simple products should be recreated as originally exported, with simple associated with group.

Actual result:
1. Group product and simple products are created, but simple are not associated with the grouped.

Have tried to import simple products only, wait for re-index then import grouped; still no association. Export CSV contains entry for _associated_skus_ set to "SKU1=1.0000,SKU2=1.0000", same as was exported.

_Copied from original issue: magento/magento2#11535_

**Comment by piotrekkaminski** [comment]
_From @magento-engcom-team on October 23, 2017 16:30_

@adamlavery, thank you for your report.
We've created internal ticket(s) MAGETWO-82532 to track progress on the issue.

**Comment by windowbox** [comment]
When can we expect this to be assigned? A huge migration project we are in the middle of is at a stop because of this. The association functionality is broken on CE, EE. We've tested on multiple hosting environments on fresh installs of 2.2.1 with no luck.

**Comment by dmanners** [comment]
Hi @windowbox we are currently in the process of putting together the prioritization for the import/export improvements. For me this feels like a high priority issue so we will aim to prioritize this problem.

The current plan for this project is to work towards the 2.3 release but of course we will also consider adding bug fixes to the 2.1 and 2.2 releases when appropriate. This could be one of those cases.

**Comment by adamlavery** [comment]
When do you think it might be released? Are we talking weeks or months? We'll need this working Jan 2018 so if there's no likelihood of a fix by then could you let us know as I'll look to do a temporary local fix in that case.

**Comment by dmanners** [comment]
@adamlavery The aim of the import/export project is to provide a release during 2.3 which is aimed for Q2 2018. Of course if the fix is backwards compatible we can always port it to 2.1 and 2.2.

**Comment by windowbox** [comment]
@adamlavery I also have put in a ticket for our EE sites and it should be designated as Priority 1 fix, the terms of which state 'Magento will use continuous efforts 24x7x365, with appropriate escalation to senior management, to provide a resolution for any P1 problem as soon as is commercially reasonable'. 

Hopefully the EE fix will shed light to fix on CW. The rep did suggest it would be after the new year but no definite timeline. My team is currently switching to associating grouped product manually, which will take a healthy amount of time considering our catalog is 5-10% grouped products.

**Comment by dmanners** [comment]
This is currently being fixed in the PR https://github.com/magento/magento2/pull/12853

**Comment by dmanners** [comment]
@mzeis I have added you here as you are planning on reviewing this pull request. Once it has been sorted out and ready to merge could you please also update this ticket?

Thank you

**Comment by mzeis** [comment]
This has been fixed for `2.3-develop` in [PR #12853](https://github.com/magento/magento2/pull/12853#event-1416312902) - see commit [38b2773e](https://github.com/magento/magento2ce/commit/38b2773ec4fb7fc0d0fd82a19ae66e7dc9c36ded).

**Comment by dmanners** [comment]
Has been done in 2.3-develop. Thank you for the information @mzeis

**Comment by sebastianrothbucher** [comment]
I guess until 2.3 (looks like around the corner anyway), setup steps and/or some SQL is the way to go. Esp. the latter is not nice, but here's one for a quick fix to bridge over (no warranty ;-) ); can be generated from CSV by Excel
```sql
insert into catalog_product_relation (parent_id, child_id) select pe.entity_id as parent_id, ce.entity_id as child_id from catalog_product_entity pe join catalog_product_entity ce where pe.sku='SR-Hoodie' and ce.sku in ('SR-Hoodie-Blue-L'); insert into catalog_product_link (product_id, linked_product_id, link_type_id) select pe.entity_id as product_id, ce.entity_id as linked_product_id_id, 3 as link_type_id from catalog_product_entity pe join catalog_product_entity ce where pe.sku='SR-Hoodie' and ce.sku in ('SR-Hoodie-Blue-L');
```
