### ISSUE TITLE
BundleImportExport is missing `selection_can_change_qty`

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#41]
_From @barryvdh on April 21, 2017 13:33_

### Preconditions
1. Magento 2.1.6

### Steps to reproduce
1. Create a Bundle product with options.
2. Export the product, no information about `selection_can_change_qty`
3. Import, no possibility to set `selection_can_change_qty`

![image](https://cloud.githubusercontent.com/assets/973269/25279627/5bd982f0-26a7-11e7-98b1-0d368fa19bae.png)

### Expected result
`selection_can_change_qty` is exported and imported correctly

### Actual result
`selection_can_change_qty` is always `true`/`1`

### Suggested solution
It seems that while importing, the value is hardcoded: https://github.com/magento/magento2/blob/2.1.6/app/code/Magento/BundleImportExport/Model/Import/Product/Type/Bundle.php#L310

I suggest a parameter `can_change_qty` will be added, while keeping the default on `1` to preserve BC.

```
'selection_can_change_qty' => (isset($selection['can_change_qty'])) ? ($selection['can_change_qty'] ? 1 : 0) : 1,
```

The value should also be added to the export of a bundle, to keep import <-> export in sync.

_Copied from original issue: magento/magento2#9342_

**Comment by piotrekkaminski** [comment]
_From @IlnitskiyArtem on June 30, 2017 15:13_

@barryvdh, Thanks for reporting this issue. We've created internal ticket MAGETWO-70390 to address this issue.

**Comment by piotrekkaminski** [comment]
_From @magento-engcom-team on October 4, 2017 9:30_

@barryvdh, thank you for your report.
We've created internal ticket(s) MAGETWO-70390 to track progress on the issue.

**Comment by adam-paterson** [comment]
@dmanners Can you assign this one to me please?

**Comment by dmanners** [comment]
@adam-paterson done, but I think you should have permission to add yourself

**Comment by adam-paterson** [comment]
Thanks, I tried but wasn’t able to self-assign it.
