### ISSUE TITLE
Magento 2.0.7 Import Products sets default behaviour as append, need add_update

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#54]
_From @Taral-Patoliya on August 17, 2016 7:29_

I am importing the products using array instead of csv, And using [FireGento_FastSimpleImport2](https://github.com/firegento/FireGento_FastSimpleImport2) Module to pass the product array to the import model. I have set the behavior of import to be  'add_append', but [getBehavior() method](https://github.com/magento/magento2/blob/develop/app/code/Magento/ImportExport/Model/Import/Entity/AbstractEntity.php#L513-L525) in the `Magento/ImportExport/Model/Import/Entity/AbstractEntity` class checks the condition and sets behavior as 'append'. I need to know why the product import does not allow `add_update` behavior? i believe that the `append`  is responsible for multiple stock item entries in the table `cataloginventory_stock_item` for same item, which generates error in the catalog product grid.

_Copied from original issue: magento/magento2#6193_

**Comment by piotrekkaminski** [comment]
_From @shiftedreality on September 9, 2016 7:9_

Hi @Taral-Patoliya 

Looks like an error to me.
Created internal ticket MAGETWO-58210 to investigate and fix.
Thank you for reporting.

**Comment by piotrekkaminski** [comment]
_From @diglin on September 19, 2017 12:36_

Also into **Magento 2.1.7** and **Magento 2.2**

Looks like an issue into the method `\Magento\ImportExport\Model\Import\Entity\AbstractEntity::getBehavior` which doesn't allow other behavior as append, replace and delete. Using custom or add_update is not allowed and fallback to append which is the default behavior

Need a PR ?

Patch in attachment


[patch_behavior_add_update_import.patch.txt](https://github.com/magento/magento2/files/1314250/patch_behavior_add_update_import.patch.txt)

**Comment by piotrekkaminski** [comment]
_From @diglin on September 19, 2017 13:34_

Why **G1 Failed** label ?

-> found myself the answer => https://github.com/magento/magento2/wiki/Magento-Issue-Gates

**Comment by piotrekkaminski** [comment]
_From @magento-engcom-team on September 22, 2017 9:6_

Hi @diglin 
PR would be always helpful. If you wish to work on that please provide clear testing scenarios and link to this issue.

Thank you for collaboration

**Comment by dmanners** [comment]
Thanks for this PR. This has now been merged into 2.3-develop.

**Comment by mflasquin** [comment]
Hi, can you tell me when this PR will be available on Magento 2.3.0 stable branch ?
Thanks
