### ISSUE TITLE
[MAGETWO-34709]  Export Customers Main File: invalid fields are available in export filter

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#62]
### Steps to reproduce: 

1. Go to System -> Export in Admin panel
2. Select f.e. Customer Main File entity type
3. Select f.e. Female gender in Filter column
4. Try to drop (remove) this filter to export both genders (without page reload)

### Actual results:
No ability to drop this filter

### Expected results:
Empty option should be present in filter to disable it

**Comment by dbolufer** [comment]
I am working on this #squashtoberfest

**Comment by valentinboyanov** [comment]
I am working on this #squashtoberfest

**Comment by davidselo** [comment]
I am working on this #squashtoberfest

**Comment by dmanners** [comment]
This has been covered by PR https://github.com/magento-engcom/import-export-improvements/pull/120. It has now been merged into 2.3-develop.
