### ISSUE TITLE
[MAGETWO-49985] Custom Options are exported in reverse order in CSV file

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#71]
### Preconditions

1. Create a simple product with two options, the 1st option is a dropdown and the 2nd option is a field, Save it

### Steps to reproduce

1. System -> Export
2. System -> Import same file 

### Expected result

1. In CSV file, the 1st option is now a dropdown and the 2nd option is a field
2. After import, in UI, the 1st option is still a dropdown and the 2nd option is a field

### Actual result

1. In CSV file, the 1st option is now a field and the 2nd option is a dropdown
2. After import, in UI, the 1st option is now a field and the 2nd option is a dropdown

**Comment by dmanners** [comment]
Fixed as part of the merge https://github.com/magento/magento2/commit/2ad32d937431d742f2d58ca6370bdd5d07d21d11
