### ISSUE TITLE
Magento 2 import products with images using CSV Issue

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#83]
_From @mayankzalavadia on July 11, 2017 14:1_

I'm trying to import a CSV file with new products that contain local images but I am receiving the error:
### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. Create simple product with image.
2. Export this product to CSV.
3. Try to import product with an image using csv.

### Expected result

Product Import Successful.

### Actual result

Got following error : 
Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s):

_Copied from original issue: magento/magento2#10209_

**Comment by piotrekkaminski** [comment]
_From @arvenzis on July 12, 2017 10:14_

I have the same problem while I do have images in the **pub/media/import** folder and in the csv the images are written like this: 123456.jpg (without the path)

**Comment by piotrekkaminski** [comment]
_From @magento-engcom-team on September 21, 2017 8:49_

Description updated.

**Comment by piotrekkaminski** [comment]
_From @magento-engcom-team on September 21, 2017 19:6_

@mayankzalavadia, thank you for your report.
We've created internal ticket(s) MAGETWO-75633 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
_From @Jens-S on September 26, 2017 8:46_

I would like to work on this ticket.

**Comment by piotrekkaminski** [comment]
_From @okorshenko on September 26, 2017 10:30_

Hi @Jens-S 
I've sent you an invitation to join Magento Team on public GitHub. Could you please accept the invitation?

**Comment by piotrekkaminski** [comment]
_From @Jens-S on September 27, 2017 20:26_

Sorry, but I want to pass this ticket back.

**Comment by piotrekkaminski** [comment]
_From @mayankzalavadia on September 28, 2017 9:35_

Hello @okorshenko 

I also would like to give my contribution on Magento. So, can you please send me an invitation to join Magento Team on public GitHub.

**Comment by piotrekkaminski** [comment]
_From @okorshenko on September 29, 2017 13:29_

@mayankzalavadia invitation sent. Would like to work on this issue?

**Comment by piotrekkaminski** [comment]
_From @mayankzalavadia on September 29, 2017 13:38_

Yes I Would like to work on this issue.

**Comment by piotrekkaminski** [comment]
_From @KarlDeux on November 14, 2017 21:18_

Cannot reproduce it on 2.2 dev.
Are you filling Images File Directory field from the admin/import tool?
If so, try not to fill it and use the CSV file exported as-is.

PS: if you still encounter issues i'd like to take care of this ticket.

**Comment by piotrekkaminski** [comment]
_From @PieterCappelle on December 21, 2017 21:39_

Can confirm. Can’t reproduce in 2.2 and 2.3.

**Comment by dmanners** [comment]
I will close this as it cannot be reproduced on 2.3 which is our focus for this project.

**Comment by KarlDeux** [comment]
Kudos @piotrekkaminski, @dmanners !
